version: '3'
services:

  #PHP Service
  app:
    image: digitalocean.com/php
    container_name: facebook_app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./php/custom.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: facebook_awebserver
    restart: unless-stopped
    tty: true
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network
  node:
    image: node:10-alpine
    container_name: node
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
      - ./docker/init-scripts/:/init-scripts/
    entrypoint:
      - /init-scripts/node_start.sh
    ports:
      - "3000:3000"
      - "3001:3001"
    networks:
      - app-network
    depends_on:
      - 'app'
  #MySQL Service
  db:
    image: mysql:5.7.22
    container_name: facebook_adb
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local
